<?php
/**
 * @file
 * localgov_base_paragraphs.module
 * Code for the LocalGov Base: Paragraphs module.
 *
 * @package   localgov_base_paragraphs
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_base_paragraphs.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function localgov_base_paragraphs_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'localgov_base_paragraphs');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}


/**
 * Implements hook_libraries_info().
 */
function localgov_base_paragraphs_libraries_info() {
  $libraries = array();
  $libraries['jquery_accessible_tabs'] = array(
    'name' => 'jQuery Accessible Tabs',
    'vendor url' => 'https://github.com/nomensa/jquery.accessible-tabs',
    'download url' => 'https://github.com/nomensa/jquery.accessible-tabs/achive/master.zip',
    'version callback' => 'localgov_base_paragraphs_version',
    'files' => array(
      'js' => array(
        'jquery.accTabs.js',
      ),
    ),
  );

  $libraries['jquery_accessible_accordion'] = array(
    'name' => 'jQuery Accessible Accordion',
    'vendor url' => 'https://github.com/nomensa/jquery.accessible-accordion',
    'download url' => 'https://github.com/nomensa/jquery.accessible-accordionachive/master.zip',
    'version callback' => 'localgov_base_paragraphs_version',
    'files' => array(
      'js' => array(
        'jquery.accAccordion.js',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_preprocess_entity().
 */
function localgov_base_paragraphs_preprocess_entity(&$variables) {
	drupal_add_js(drupal_get_path('module', 'localgov_base_paragraphs') . '/js/localgov_base_paragraphs.js');

  if ($variables['elements']['#bundle'] == 'tabs' && $variables['elements']['#entity_type'] == 'paragraphs_item') {
    libraries_load('jquery_accessible_tabs');
  }

  if ($variables['elements']['#bundle'] == 'accordion' && $variables['elements']['#entity_type'] == 'paragraphs_item') {
    libraries_load('jquery_accessible_accordion');
  }

  // If the highlight paragraph has an icon, output a class to style the paragraph differently.
  if ($variables['elements']['#bundle'] == 'highlighted' && $variables['elements']['#entity_type'] == 'paragraphs_item') {
    if (isset($variables['field_icon'])) {
      $variables['classes_array'][] = 'highlight-has-icon';
    }
  }

  // Output different classes to swap the layout of the content and media depending on which layout is chosen by the content editor.
  if ($variables['elements']['#entity_type'] == 'paragraphs_item' && $variables['elements']['#bundle'] == 'promotional_area') {

    $variables['content_position'] = '';
    $variables['image_position'] = '';
    $image_position = $variables['elements']['field_promotional_area_layout']['#items'][0]['value'];

    if ($image_position == 'left') {
      $variables['classes_array'][] = 'promotional-area-media-left';
      $variables['content_position'] = 'col-md-push-6';
      $variables['image_position'] = 'col-md-pull-6';
    }
  }

  // Add variables to display the grid display based on content editor choices.
  if ($variables['elements']['#entity_type'] == 'paragraphs_item' && $variables['elements']['#bundle'] == 'grid_display') {
    $variables['classes_array'][] = 'grid-display';

    $grid_display_title_text = $variables['field_grid_display_title'][0]['value'];
    $grid_display_title_level = $variables['field_grid_display_title_level'][0]['value'];
    $grid_display_theme = $variables['field_grid_display_theme'][0]['value'];

    // Add heading level and heading text as variables so we can provide better accessibility support.
    if (!empty($grid_display_title_text) && !empty($grid_display_title_level)) {
      $variables['grid_display_title_text'] = $grid_display_title_text;
      $variables['grid_display_title_level'] = $grid_display_title_level;
    }

    // Add the theme type as a variable.
    if (!empty($grid_display_theme)) {
      $variables['classes_array'][] = 'grid-display-' . $grid_display_theme;
    }
  }
}

/**
 * Short-circuit the version argument.
 */
function localgov_base_paragraphs_version() {
  return TRUE;
}
