<?php
/**
 * @file
 * bracknell_feature_beta.features.field_instance.inc
 * TODO: Add file description
 *
 * @package   bracknell_feature_beta
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

 /**
  * Implements hook_field_default_field_instances().
  */
 function bracknell_feature_beta_field_default_field_instances() {
   $field_instances = array();

   return $field_instances;
 }
