<?php

/**
 * @file
 * Code for the Bracknell Entity External Link feature.
 */

include_once 'bracknell_entity_external_link.features.inc';

/**
 * Implements hook_theme().
 */
function bracknell_entity_external_link_theme() {
  $theme = array();
  $theme['external_link__external_link'] = array(
    'render element' => 'elements',
    'template' => 'external_link--external_link',
    'path' => drupal_get_path('module', 'bracknell_entity_external_link') . '/templates',
  );
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * This will ensure that any external links are rendered with the link url
 * and not a link to the entity. Currently this has been used on the 
 * field_top_tasks but may also apply to any new related link elements.
 */
function bracknell_entity_external_link_preprocess_field(&$variables) {
  // Do not alter in admin views.
  if (path_is_admin(current_path())) {
    return;
  }

  if ($variables['element']['#field_name'] == 'field_top_tasks') {
    // Get the accompanying object - node assumed.
    $node_wrapper = entity_metadata_wrapper('node', $variables['element']['#object']);
    if (!empty($node_wrapper)) {
      $values = $node_wrapper->get('field_top_tasks')->value();
      if (!empty($values) && is_array($values)) {
        foreach ($values as $index => $link) {
          if ($link['target_type'] == 'external_link') {
            // Get the external_link entity.
            $link_wrapper = entity_metadata_wrapper('external_link', $link['entity']);
            // Get the information from the entity.
            $new_title = $link_wrapper->get('field_link_url')->get('title')->value();
            $new_url = $link_wrapper->get('field_link_url')->get('url')->value();
            // Reset the link to show actual url.
            $variables['items'][$index]['#markup'] = l(t($new_title), $new_url);
          }
        }
      }
    }
  }
}
