<?php
/**
 * @file
 * localgov_base_config.features.field_base.inc
 * TODO: Add file description
 *
 * @package   localgov_base_config
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

 /**
  * Implements hook_field_default_field_bases().
  */
 function localgov_content_directory_field_default_field_bases() {
   $field_bases = array();

   return $field_bases;
 }
