<?php
/**
 * @file
 * localgov_content_fact.module
 * Code for the LocalGov Content: Fact module.
 *
 * @package   localgov_content_fact
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_content_fact.features.inc';

/**
 * Implements hook_theme().
 */
function localgov_content_fact_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__fact'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--fact',
    'path' => drupal_get_path('module', 'localgov_content_fact') . '/templates',
   );
   $theme['field__field_fact_link'] = array(
     'render element' => 'content',
     'base hook' => 'field',
     'template' => 'field--field-fact-link',
     'path' => drupal_get_path('module', 'localgov_content_fact') . '/templates',
    );
  return $theme;
}
