<?php
/**
 * @file
 * localgov_feature_related.module
 * Code for the LocalGov Feature: Related module.
 *
 * @package   localgov_feature_related
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_feature_related.features.inc';

/**
 * Implements hook_form_alter().
 */
function localgov_feature_related_form_alter(&$form, &$form_state, $form_id, $node) {
  if (strpos($form_id, 'node_form')) {
    // Implement afterbuild
    $form['#after_build'][] = '_localgov_feature_related_form_organize';
    // Implement validate to avoid errors & notices
    $form['#validate'][] = '_localgov_feature_related_form_validate';
  }
}

/**
 * Implements hook_preprocess_block().
 */
function localgov_feature_related_preprocess_block(&$variables) {
  $block_id = $variables['block']->module . '-' . $variables['block']->delta;
  $classes = &$variables['classes_array'];

  // Output classes depending on the block id.
  switch($block_id) {
    case 'views-related_links_node-block':
      $classes[] = 'related-links';
    break;
  }
}
