<?php
/**
 * @file
 * Code for the Bracknell Feature: Landing Page feature.
 */

include_once 'bracknell_feature_landing_page.features.inc';

/**
 * Implements hook_theme().
 */
function bracknell_feature_landing_page_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__landing_page'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--landing-page',
    'path' => drupal_get_path('module', 'bracknell_feature_landing_page') . '/templates',
   );
  return $theme;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bracknell_feature_landing_page_form_node_form_alter(&$form) {
  if (empty($form['field_theme'])) {
    return;
  }

  $element = &$form['field_theme'][LANGUAGE_NONE];

  // Ensure that the "default" option is pre-selected.
  if (empty($element['#value_key'])) {
    $form['field_theme'][LANGUAGE_NONE]['#default_value'] = 'default';
  }
}
