<?php
/**
 * @file
 * Code for the Bracknell Feature: Landing Page feature.
 */

include_once 'bracknell_feature_landing_page.features.inc';

/**
 * Implements hook_theme().
 */
function bracknell_feature_landing_page_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__landing_page'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--landing-page',
    'path' => drupal_get_path('module', 'bracknell_feature_landing_page') . '/templates',
   );
  return $theme;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bracknell_feature_landing_page_form_node_form_alter(&$form) {
  if (empty($form['field_theme'])) {
    return;
  }

  $element = &$form['field_theme'][LANGUAGE_NONE];

  // Ensure that the "default" option is pre-selected.
  if (empty($element['#value_key'])) {
    $form['field_theme'][LANGUAGE_NONE]['#default_value'] = 'default';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bracknell_feature_landing_page_preprocess_html(&$variables) {
  if (path_is_admin(current_path())) {
    return;
  }

  if ($node = menu_get_object()) {
    $wrapper = entity_metadata_wrapper('node', $node);

    if (!empty($node->field_theme)) {
      _bracknell_feature_landing_page_add_theme_class_to_page($wrapper, $variables);
    }
    else {
      // TODO: Apply class to sub-pages once the sections have been re-structured.
    }
  }
}

/**
 * Add a theme class to pages.
 *
 * @param \EntityDrupalWrapper $wrapper
 *   The metadata wrapper of the node being viewed.
 * @param array $variables
 *   The variables from the preprocess function.
 *
 * @internal param \stdClass $node The node being viewed.*   The node being viewed.
 * @see bracknell_feature_landing_page_preprocess_html()
 */
function _bracknell_feature_landing_page_add_theme_class_to_page(EntityDrupalWrapper $wrapper, array &$variables) {
  $variables['classes_array'][] = 'theme-' . $wrapper->get('field_theme')->value();
}
