<?php
/**
 * @file
 * Code for the Bracknell Feature: Landing Page feature.
 */

include_once 'bracknell_feature_landing_page.features.inc';

/**
 * Implements hook_theme().
 */
function bracknell_feature_landing_page_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__landing_page'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--landing-page',
    'path' => drupal_get_path('module', 'bracknell_feature_landing_page') . '/templates',
   );
  return $theme;
}

