<?php
/**
 * @file
 * localgov_base_cookies.module
 * Code for the LocalGov Base: Cookies module.
 *
 * @package   localgov_base_cookies
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_base_cookies.features.inc';

/**
 * Implements template_preprocess_html().
 */
function localgov_base_cookies_preprocess_html(&$variables) {
  drupal_add_css(drupal_get_path('module', 'localgov_base_cookies') . '/css/cookieconsent.min.css');
  drupal_add_js(drupal_get_path('module', 'localgov_base_cookies') . '/js/cookieconsent.min.js');
  drupal_add_js('window.addEventListener("load", function() {
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#336633",
        "text": "#ffffff"
      },
      "button": {
        "background": "#ffffff",
        "text": "#070510"
      }
    },
    "content": {
      "message": "We use cookies to improve your visit to this site. By viewing our content you are accepting the use of cookies.",
      "dismiss": "Continue",
      "link": "Find out more about how we use cookies",
      "href": "/smallprint/cookies"
    }
  })});', array('type' => 'inline'));
}
