<?php
/**
 * @file
 * localgov_base_cookies.module
 * Code for the LocalGov Base: Cookies module.
 *
 * @package   localgov_base_cookies
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_base_cookies.features.inc';

/**
 * Implements hook_library().
 */
function localgov_base_cookies_library() {

  // Cookie Consent.
  $libraries['cookie-consent'] = array(
    'title' => 'Cookie Consent',
    'website' => 'https://cookieconsent.insites.com/download/',
    'version' => '3.0',
    'js' => array(
      drupal_get_path('module', 'localgov_base_cookies') . '/js/cookieconsent-init.js' => array(),
      drupal_get_path('module', 'localgov_base_cookies') . '/js/cookieconsent.min.js' => array(),
    ),
    'css' => array(
       drupal_get_path('module', 'localgov_base_cookies') . '/css/cookieconsent.min.css' => array(),
    ),
  );

  return $libraries;
}

function localgov_base_cookies_preprocess_page(&$variables) {
  // Only load the cookie consent library on pages which are not admin pages.
  if (!path_is_admin(current_path())) {
    drupal_add_library('localgov_base_cookies', 'cookie-consent');
  }
}
