<?php
/**
 * @file
 * Code for the Bracknell Feature: Search feature.
 */

/**
 * Standard Features include.
 */
include_once 'bracknell_feature_search.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add custom JS to the search page.
 */
function bracknell_feature_search_form_views_exposed_form_alter(&$form, &$form_state) {
  // Add the custom JS file to the Search page only.
  if ($form['#id'] == 'views-exposed-form-search-page-page') {
    $form['#attached']['js'][] = drupal_get_path('module', 'bracknell_feature_search') . '/js/searchFunctions.js';
    $form['search_api_views_fulltext']['#attributes']['placeholder'] = t('Search this site');
    $form['submit']['#attributes']['class'][] = 'icon';
    $form['submit']['#attributes']['class'][] = 'theme-icon-search';
    $form['submit']['#value'] = '';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function bracknell_feature_search_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'bracknell_feature_search');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
