<?php
/**
 * @file
 * Code for the Bracknell Feature: Search feature.
 */

/**
 * Standard Features include.
 */
include_once 'bracknell_feature_search.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add custom JS to the search page.
 */
function bracknell_feature_search_form_views_exposed_form_alter(&$form, &$form_state) {
  // Add the custom JS file to the Search page only.
  if ($form['#id'] == 'views-exposed-form-search-page-page') {
    $form['#attached']['js'][] = drupal_get_path('module', 'bracknell_feature_search') . '/js/searchFunctions.js';
    $form['search_api_views_fulltext']['#attributes']['placeholder'] = t('Search this site');
    $form['submit']['#attributes']['class'][] = 'icon';
    $form['submit']['#attributes']['class'][] = 'glyphicon';
    $form['submit']['#attributes']['class'][] = 'glyphicon-search';
    $form['submit']['#value'] = '';
  }
}
