<?php

/**
 * @file
 * Contains the hooks and functions to implement Readspeaker.
 */

/**
 * Implements hook_form_alter().
 */
function bracknell_readspeak_form_alter(&$form, &$form_state, $form_id) {
  // Attach the Readspeak javascript to the page.
  // TODO: add variable for Readspeak to improve performance.
  $form['#attached']['js'] = array(
    '//f1-eu.readspeaker.com/script/5766/ReadSpeaker.js?pids=embhl' => array(
      'type' => 'external',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bracknell_readspeak_preprocess_page(&$variables) {
  // TODO: add a readspeak variable and check it's status to suggest template.
  $variables['theme_hook_suggestions'][] = 'page__readspeak';
  
  // Define a new title variable - text only.
  if (!empty($node = $variables['node'])) {
    $variables['rs_title'] = $node->title;
  }
  
  // Define a path for the Readspeak JS
  $variables['rs_path'] = $GLOBALS['base_url'] . request_uri();
}

/**
 * Implements hook_theme_registry_alter().
 */
function bracknell_readspeak_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'bracknell_readspeak');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}