<?php
/**
 * @file
 * localgov_base_admin.module
 * Code for the LocalGov Base: Admin module.
 *
 * @package   localgov_base_admin
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_base_admin.features.inc';

/**
 * Implements hook_theme().
 */
function localgov_base_admin_theme($existing, $type, $theme, $path) {
  $items = array();
  // Core menu theming overrides.
  $items['menu_tree__localgov'] = array(
    'render element' => 'tree',
    'function' => 'theme_navbar_menu_tree',
    'preprocess functions' => array('template_preprocess_navbar_menu_tree'),
    'file' => 'navbar.module',
    'path' => drupal_get_path('module', 'navbar')
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function localgov_base_admin_admin_paths() {
  $paths = array(
    'admin/localgov/*' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_navbar_alter().
 */
function localgov_base_admin_navbar_alter(&$items) {
  if (user_access('access drupal admin')) {
    $items['administration']['tab']['#title'] = t('Drupal Admin');
  }
  else {
    unset($items['administration']);
  }
}

/**
 * Implements hook_views_api().
 */
function localgov_base_admin_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array(
      'version' => 2
    );
  }
}
