<?php
/**
 * @file
 * localgov_base_content.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function localgov_base_content_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'body'.
  $field_bases['body'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(
      0 => 'node',
    ),
    'field_name' => 'body',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_with_summary',
  );

  // Exported field_base: 'field_description'.
  $field_bases['field_description'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_description',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_icon'.
  $field_bases['field_icon'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_icon',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'theme-icon-circle-dark-exclamation' => '<span class="icon theme-icon-circle-dark-exclamation"></span> Circle Dark - Exclamation',
        'theme-icon-circle-dark-question' => '<span class="icon theme-icon-circle-dark-question"></span> Circle Dark - Question',
        'theme-icon-cross' => '<span class="icon theme-icon-cross"></span> Cross',
        'theme-icon-download' => '<span class="icon theme-icon-download"></span> Download',
        'theme-icon-external-link' => '<span class="icon theme-icon-external-link"></span> External Link',
        'theme-icon-question' => '<span class="icon theme-icon-question"></span> Question',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
