<?php
/**
 * @file
 * localgov_feature_contactinfo.features.field_instance.inc
 * TODO: Add file description
 *
 * @package   localgov_feature_contactinfo
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

 /**
  * Implements hook_field_default_field_instances().
  */
 function localgov_feature_contactinfo_field_default_field_instances() {
   $field_instances = array();

   return $field_instances;
 }
