<?php
/**
 * @file
 * localgov_feature_contactinfo.module
 * Code for the LocalGov Feature: Contact Information module.
 *
 * @package   localgov_feature_contactinfo
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_feature_contactinfo.features.inc';

/**
 * Implements hook_form_alter().
 */
function localgov_feature_contactinfo_form_alter(&$form, &$form_state, $form_id, $node) {
  if (strpos($form_id, 'node_form')) {
    // Implement afterbuild
    $form['#after_build'][] = '_localgov_feature_contactinfo_form_organize';
    // Implement validate to avoid errors & notices
    $form['#validate'][] = '_localgov_feature_contactinfo_form_validate';
  }
}

/**
 * Implements hook_views_api().
 */
function localgov_feature_contactinfo_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array('version' => 2);
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function localgov_feature_contactinfo_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'localgov_feature_contactinfo');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

