<?php
/**
 * @file
 * localgov_feature_contactinfo.module
 * Code for the LocalGov Feature: Contact Information module.
 *
 * @package   localgov_feature_contactinfo
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_feature_contactinfo.features.inc';

/**
 * Implements hook_form_alter().
 */
function localgov_feature_contactinfo_form_alter(&$form, &$form_state, $form_id, $node) {
  if (strpos($form_id, 'node_form')) {
    // Implement afterbuild
    $form['#after_build'][] = '_localgov_feature_contactinfo_form_organize';
    // Implement validate to avoid errors & notices
    $form['#validate'][] = '_localgov_feature_contactinfo_form_validate';
  }
}

/**
 * Implements hook_views_api().
 */
function localgov_feature_contactinfo_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array('version' => 2);
  }
}
