<?php
/**
 * @file
 * localgov_base_taxonomy.module
 * Code for the LocalGov Base: Taxonomy module.
 *
 * @package   localgov_base_taxonomy
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Include features code.
 */
include_once 'localgov_base_taxonomy.features.inc';

/**
 * Implements hook_theme().
 */
function localgov_base_taxonomy_theme() {
  return array(
    'localgov_base_taxonomy_overview_vocabularies' => array(
      'render element' => 'form',
    ),
    'localgov_base_taxonomy_overview_terms' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function localgov_base_taxonomy_form_alter(&$form, &$form_state, $form_id, $node) {
  if (strpos($form_id, 'node_form')) {
    // Implement afterbuild
    $form['#after_build'][] = '_localgov_base_taxonomy_form_organize';
    // Implement validate to avoid errors & notices
    $form['#validate'][] = '_localgov_base_taxonomy_form_validate';
  }
}
