<?php
/**
 * @file
 * localgov_feature_guide.module
 * Code for the LocalGov Feature: Guide module.
 */

// Include all inc files.
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

// Include features code.
include_once 'localgov_feature_guide.features.inc';

/**
 * Implements hook_theme().
 */
function localgov_feature_guide_theme($existing, $type, $theme, $path) {
  return array(
    'node__guide' => array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'node--guide',
      'path' => drupal_get_path('module', 'localgov_feature_guide') . '/templates',
    ),
    'node__guide_section' => array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'node--guide_section',
      'path' => drupal_get_path('module', 'localgov_feature_guide') . '/templates',
    ),
  );
}


/**
 * Implements hook_process_html().
 */
function localgov_feature_guide_process_html(&$variables) {
  // Use the guide title (rather than guide section) for the page title.
  $node = menu_get_object();
  if ($node && $node->type === 'guide_section') {
    $parent = menu_link_load($node->guide['plid']);
    $variables['head_title_array']['title'] = $parent['link_title'];
    $variables['head_title'] = implode(' | ', $variables['head_title_array']);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function localgov_feature_guide_preprocess_page(&$variables) {
  // Use the guide title (rather than guide section) for the page title.
  if (isset($variables['node']) && $variables['node']->type === 'guide_section') {
    $parent = menu_link_load($variables['node']->guide['plid']);
    $variables['title'] = $parent['link_title'];
  }

  // Create the previous and next section links.
  if (isset($variables['node']) && $variables['node']->type === 'guide') {
    $guide_link = menu_link_load($variables['node']->guide['mlid']);
    if ($guide_link['mlid']) {
      $next = guide_next($guide_link);
      if ($next) {
        $next_href = url($next['href']);
        drupal_add_html_head_link(array('rel' => 'next', 'href' => $next_href));
        $variables['node']->guide['next_url'] = $next_href;
        $variables['node']->guide['next_title'] = check_plain($next['title']);
      }
    }
  }

  // Get the object and do some other checks based on what you need.
  if (isset($variables['node']) && in_array($variables['node']->type, array('guide', 'guide_section'))) {
    // Generate a render array for the node.
    $view = node_view($variables['node']);
    // Supply the guide_menu variable to the page.tpl.php file.
    $variables['guide_menu'] = drupal_render($view['guide_navigation_primary']);
  }
}
