<?php

include_once 'bracknell_base.features.inc';

/**
 * Implements hook_theme().
 */
function bracknell_base_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['field__field_related_pages_view'] = array(
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--field-related-pages-view',
    'path' => drupal_get_path('module', 'bracknell_base') . '/templates',
  );
  $theme['field__field_promotional_hero'] = array(
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--field-promotional-hero',
    'path' => drupal_get_path('module', 'bracknell_base') . '/templates',
  );
  return $theme;
}
