<?php
/**
 * @file
 * Code for the Bracknell Base feature.
 */

include_once 'bracknell_base.features.inc';

/**
 * Implements hook_theme().
 */
function bracknell_base_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['field__field_related_pages'] = array(
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--field-related-pages',
    'path' => drupal_get_path('module', 'bracknell_base') . '/templates',
  );
  $theme['field__field_related_links'] = array(
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--field-related-links',
    'path' => drupal_get_path('module', 'bracknell_base') . '/templates',
  );
  $theme['field__field_related_pages_view'] = array(
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--field-related-pages-view',
    'path' => drupal_get_path('module', 'bracknell_base') . '/templates',
  );
  $theme['field__field_related_links_view'] = array(
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--field-related-links-view',
    'path' => drupal_get_path('module', 'bracknell_base') . '/templates',
  );
  $theme['field__field_promotional_hero'] = array(
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--field-promotional-hero',
    'path' => drupal_get_path('module', 'bracknell_base') . '/templates',
  );
  return $theme;
}

/**
 * Implements hook_preprocess_node().
 */
function bracknell_base_preprocess_node(&$variables) {
  if (!empty($variables['field_promotional_hero']) >= 1) {
    $variables['classes_array'][] = 'promotional-hero-has-image';
  }
}
