<?php
/**
 * @file
 * guide.features.user_permission.inc
 * TODO: Add file description
 *
 * @package   guide
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Implements hook_user_default_permissions().
 */
function guide_user_default_permissions() {
  $permissions = array();

  return $permissions;
}
