<?php
/**
 * @file
 * localgov_base_pages.module
 * Code for the LocalGov Base: Pages module.
 *
 * @package   localgov_base_pages
 * @author    Craig Gardener <craig.gardener@bracknell-forest.gov.uk>
 * @copyright Copyright (c) 2016, Craig Gardener
 * @license   http://opensource.org/licenses/gpl-license.php
 *            GNU General Public License, version 2 or later
 */

/**
 * Include all files in 'includes/'.
 */
foreach (glob(__DIR__ . '/includes/*.inc') as $filename) {
  include_once $filename;
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * types of plugins: layouts, styles, args, contexts, content_types.
 */
function localgov_base_pages_ctools_plugin_directory($owner, $plugin_type) {
  // We're just providing layout plugins.
  if ($owner == 'panels' && $plugin_type == 'layouts') {
    // localgov_base_pages_ctools_plugin_directory.
    return "plugins/$plugin_type";
  }
}
